Sphereon-Opensource/OID4VC

lib/functions/HttpUtils.ts
Changed the fallback `headers` to an empty object instead of array.
Fixes #18 
Signed-off-by: Karim Stekelenburg <karim@animo.id>
=> fix: wrong headers type

package.json
The move of the `@sphereon/ssi-types` dependency to `devDependencies` broke my installation as the build includes imports to that package. 
Signed-off-by: Karim Stekelenburg <karim@animo.id>
=> fix: ssi-types dependency

lib/types/Authorization.types.ts
I've noticed that the scope was not present on the `AccessTokenResponse`
type. However, the scope is set whenever using an issuer URI that
contains a `credential_type`.
Signed-off-by: Karim Stekelenburg <karim@animo.id>
=> fix: add scope to AccessTokenResponse

packages/client/lib/CredentialRequestClient.ts, packages/client/lib/__tests__/CredentialRequestClient.spec.ts, packages/client/lib/__tests__/IT.spec.ts, packages/client/lib/__tests__/data/VciDataFixtures.ts, packages/common/lib/types/Generic.types.ts, packages/issuer/lib/VcIssuer.ts, pnpm-lock.yaml
According to https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-e.1 the format identifier for a VC signed as a JWT, using JSON-ld is `jwt_vc_json-ld`.
(a better fix might be to keep the format identifiers in an enum and reuse them form there.)
=> fix: rename jwt_vc_json_ld to jwt_vc_json-ld

packages/callback-example/lib/__tests__/issuerCallback.spec.ts, packages/client/lib/AuthorizationDetailsBuilder.ts, packages/client/lib/CredentialRequestClient.ts, packages/client/lib/CredentialRequestClientBuilder.ts, packages/client/lib/OpenID4VCIClient.ts, packages/client/lib/__tests__/CredentialRequestClient.spec.ts, packages/client/lib/__tests__/data/VciDataFixtures.ts, packages/common/lib/functions/CredentialOfferUtil.ts, packages/common/lib/functions/CredentialRequestUtil.ts, packages/common/lib/functions/FormatUtils.ts, packages/common/lib/functions/IssuerMetadataUtils.ts, packages/common/lib/functions/index.ts, packages/common/lib/types/Authorization.types.ts, packages/common/lib/types/Generic.types.ts, packages/common/lib/types/v1_0_08.types.ts, packages/common/lib/types/v1_0_11.types.ts, packages/issuer-rest/lib/__tests__/IssuerTokenServer.spec.ts, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/__tests__/VcIssuer.spec.ts, packages/issuer/lib/builder/CredentialSupportedBuilderV1_11.ts, packages/tsconfig.json
Adds support for `vc+sd-jwt` format as described in https://github.com/vcstuff/oid4vc-haip-sd-jwt-vc
Because the format specific for `vc+sd-jwt` are a bit different than the other formats, it exposed some issues with the types currently being used. I updated all interfaces, made the uniform interfaces match draft 11 fully, and moved some v8/9 specific types outside of the uniform/generic types.
Because the types are different, and it exposed some issues with the current way requests are being made, there's more format speicfic logic now inline. I've didn't want to make this PR bigger than it currently is, so I've created a separate issue #76, to explore that work.
All tests are passing except the e2e test with mattr launchpad, as it's currently down for maintenance. In addition I had to …
=> feat: add sd-jwt support

packages/callback-example/lib/IssuerCallback.ts, packages/callback-example/lib/__tests__/issuerCallback.spec.ts, packages/callback-example/package.json, packages/client/lib/CredentialRequestClient.ts, packages/client/lib/OpenID4VCIClient.ts, packages/client/lib/ProofOfPossessionBuilder.ts, packages/client/lib/__tests__/SdJwt.spec.ts, packages/client/lib/functions/ProofUtil.ts, packages/client/package.json, packages/common/lib/functions/CredentialOfferUtil.ts, packages/common/lib/functions/CredentialRequestUtil.ts, packages/common/lib/functions/IssuerMetadataUtils.ts, packages/common/lib/types/Authorization.types.ts, packages/common/lib/types/Generic.types.ts, packages/common/lib/types/QRCode.types.ts, packages/common/package.json, packages/issuer-rest/package.json, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/builder/CredentialSupportedBuilderV1_11.ts, packages/issuer/lib/types/index.ts, packages/issuer/package.json, pnpm-lock.yaml
This PR builds on top of https://github.com/Sphereon-Opensource/OID4VCI/pull/78, and adds support for issuance side for sd-jwt vcs as well as adds an e2e test using sd-jwt vcs
~~Dependant on https://github.com/Sphereon-Opensource/SSI-SDK/pull/145 to be merged and released~~
=> feat: add sd-jwt issuer support and e2e test

packages/callback-example/package.json, packages/client/package.json, packages/common/package.json, packages/issuer-rest/package.json, packages/issuer/lib/VcIssuer.ts, packages/issuer/package.json, pnpm-lock.yaml
small fix to use `cnf` object instead of `sub` property for binding the sd-jwt as defined in the sd-jwt vc spec.
Also adds support for `kid` (did) binding in addition to jwk binding for an sd-jwt
=> fix(sd-jwt): cnf instead of kid

packages/issuer/package.json
We have a combined `@credo-ts/openid4vc` package that depends on the common, issuer and client libraires.
When importing this into react native it is giving us some issues because RN resolves conditional imports to bundle in the JS bundle and awesome-qr is an optional dependnecy.
We could add awesome-qr as a dependency and it'd then bundle awesome-qr with our app, but adding a `react-native` clause to the issuer package also solves the issue
It will limit the usage of creating a QR when creating an offer, but then someone will need to a) write an issuer in React Native and b) use the QR generation options. And even then is the question whether this package works in React Native.
It seemed like a valid workaround. But i can also just add the dependency to the bundle if you think we …
=> fix: disable awesome-qr in rn

packages/common/lib/types/OpenID4VCIErrors.ts, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/__tests__/VcIssuer.spec.ts
As a reference to #88, this Pull Request allows developers to use the given `Alg` list or a signing algorithm of their choice by just checking that the `alg` field is provided without verifying if its value is part of the `Alg` enum.
Some tests have been re-enabled, added and modified to have some coverage on this part.
=> Open the signing algorithm list in the credential issuance process

packages/callback-example/lib/__tests__/issuerCallback.spec.ts, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/state-manager/LookupStateManager.ts, packages/issuer/lib/tokens/index.ts
Some state updates (set, delete) were not awaited. When updating the in memory session manager to one that uses persistance storage we were running into issues were we would close our database session (as the call to this library is finished), but then a write would still happen as the updates to the session were not awaited.
Were these awaits left out on purpose?
=> fix: await session state updates

packages/common/lib/functions/CredentialRequestUtil.ts, packages/common/lib/types/v1_0_11.types.ts
The type was incorrectly set, as according to draft 11 of OID4VCI the LDP credential request MUST have a `credential_definition` object.
The same is true for draft 12.
The code still works with top-level types as well, (as currently both `credential_definition.types` and `types` already worked), but the type is corrected now.
=> fix: type for cred request ldp

packages/callback-example/lib/__tests__/issuerCallback.spec.ts, packages/client/lib/__tests__/SdJwt.spec.ts, packages/issuer-rest/lib/__tests__/ClientIssuerIT.spec.ts, packages/issuer-rest/lib/__tests__/IssuerTokenServer.spec.ts, packages/issuer-rest/lib/oid4vci-api-functions.ts, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/__tests__/VcIssuer.spec.ts, packages/issuer/lib/tokens/index.ts
Seems there were some other places were milliseconds were used, but the specs describe to use seconds for `iat`, `exp`, `c_nonce_expires_in`, `interval` and `expires_in`
I modified some defaults, so this is technically a breaking change, but I think the current implementation is incorrect so it could also be seen as a fix I think.
=> fix: use seconds for all expires in values

packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/functions/CredentialOfferUtils.ts
another fix related to milliseconds vs seconds
=> fix: seconds to ms

packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/tokens/index.ts
This PR fixes two small problems.
In the VcIssuer file, the issuer is determined by decoding the credential into a standardized format with an issuer field.
Decoding the issuer requires a hash implementation for compact sdjwt's. To work around this, I made the issuer an argument.
The second problem concerns the implementation of token validation in combination with a PIN and compatibility with v11 and v13.
=> fix: sdjwtvc decode hasher dependency

packages/client/lib/AuthorizationCodeClient.ts, packages/client/lib/AuthorizationCodeClientV1_0_11.ts, packages/client/lib/CredentialRequestClient.ts, packages/client/lib/OpenID4VCIClient.ts, packages/client/lib/__tests__/CredentialRequestClientBuilder.spec.ts, packages/client/lib/__tests__/SdJwt.spec.ts, packages/common/lib/functions/CredentialRequestUtil.ts, packages/common/lib/functions/IssuerMetadataUtils.ts, packages/common/lib/functions/TypeConversionUtils.ts, packages/common/lib/types/Generic.types.ts, packages/common/lib/types/v1_0_11.types.ts, packages/common/lib/types/v1_0_13.types.ts, packages/did-auth-siop-adapter/README.md, packages/issuer/lib/__tests__/VcIssuer.spec.ts, packages/issuer/lib/builder/CredentialSupportedBuilderV1_13.ts, packages/siop-oid4vp/lib/__tests__/DidJwtTestUtils.ts
A lot of the typing for draft 13 was not according to the spec. I also separated some type definitions per format so we have better type completion. We noticed when integrating draft 13 vs draft 11 in Credo that with draft 13 we lost a lost of format specific typing, which made using the library a lot easier. This aims to bring it back.
With the updates of the types I also discovered some bugs related to transformations, and which keys were used (e.g. `types` for v11 were still used for v13 even though it should be `type` now. As well as request in v13 needs to use `credential_definition` for jwt vc json as well now, which in v11 was still top-level).
=> fix: oid4vci draft 13 typing

packages/client/lib/AuthorizationCodeClient.ts, packages/client/lib/__tests__/OpenID4VCIClient.spec.ts, packages/client/lib/__tests__/OpenID4VCIClientV1_0_13.spec.ts
This PR makes two changes:
- prioritise authorization server metadata over issuer metadata for PAR requirements (Funke issuer adds it in authorization server metadata)
- do not include `openid` scope if not included. I can't find in the specs where this is a requirement, and the funke PID issuer will not grant this scope. I think it makes more sense to let the user pass the scope `openid` if it wants this scope.
=> fix: scope and par fixes

packages/client/lib/AccessTokenClient.ts, packages/common/lib/types/Authorization.types.ts, packages/issuer/lib/VcIssuer.ts, packages/issuer/lib/tokens/index.ts
Fix for the bug in https://github.com/Sphereon-Opensource/OID4VC/commit/7d17d13d3485c5b6b55ef876eba8f09c9f7a788b
As explained in the comment there, the line below will overwrite the set value for the pin.
We do not need to store the value of `txCode` since this is already in the grant. So it's fine to remove this line without any side effects.
=> fix: remove bug for txCode

packages/common/lib/types/Generic.types.ts
some additional type fixes for v11 metadata
=> fix: v11 metadata type

packages/common/lib/jwt/JwkThumbprint.ts, packages/common/lib/jwt/__tests__/JwkThumbprint.spec.ts
Small error in the jwk thumbprint digest. Now also added a test based on the jwk thumbprint spec to ensure correctness
=> fix: jwk thumbprint digest

packages/common/lib/jwt/JwtIssuer.ts, packages/oid4vci-common/lib/types/CredentialIssuance.types.ts, packages/siop-oid4vp/lib/request-object/Payload.ts, packages/siop-oid4vp/lib/request-object/RequestObject.ts, packages/siop-oid4vp/lib/rp/RPBuilder.ts, packages/siop-oid4vp/lib/schemas/AuthorizationResponseOpts.schema.ts, packages/siop-oid4vp/lib/types/SIOP.types.ts, pnpm-lock.yaml
A small PR to fix the current client_id_scheme and default scope scope handling.
* Removes the client_id_scheme from the client_metadata (should not be there)
* Removes the cliend_id_scheme from the jwtIssuerX5C (because we also need the client_id_scheme when x5c is not used)
* Add builder method for setting the client_id_scheme
* Remove the openid default scope, it is not required.
=> fix: client_id_scheme & default scope handling

packages/common/lib/jwt/JwtVerifier.ts, packages/siop-oid4vp/lib/authorization-response/Payload.ts
Some fixes that were needed to pass the OID4VC conformance test suite (we are now passing).
=> fix: changes for oid4vc conformance tests

packages/issuer/lib/tokens/index.ts
Very simple PR to allow additional access token claims in the generateAccessToken method
=> feat: allow additional claims in access token

packages/siop-oid4vp/lib/__tests__/IT.spec.ts, packages/siop-oid4vp/lib/__tests__/SdJwt.spec.ts, packages/siop-oid4vp/lib/authorization-response/AuthorizationResponse.ts, packages/siop-oid4vp/lib/authorization-response/OpenID4VP.ts
=> chore: unwrap single-element array in extractPresentationsFromVpToken

packages/siop-oid4vp/lib/authorization-response/PresentationExchange.ts
small improvement to show the error reason if returned by the method. It was swallowed because of the try catch
=> fix: use error reason if provided
